# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('device_ip', models.CharField(max_length=100, verbose_name='\u8bbe\u5907IP')),
                ('device_devtype', models.CharField(choices=[('\u6444\u50cf\u673a', '\u6444\u50cf\u673a'), ('\u7f16\u7801\u5668', '\u7f16\u7801\u5668'), ('\u89e3\u7801\u5668', '\u89e3\u7801\u5668'), ('\u5176\u4ed6', '\u5176\u4ed6')], max_length=200, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('device_vendor', models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u5382\u5546')),
                ('device_signer', models.CharField(default='system', max_length=100, verbose_name='\u767b\u8bb0\u4eba')),
                ('device_signtime', models.DateField(auto_now_add=True)),
                ('device_remarks', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='echo.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_code', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668\u7f16\u53f7')),
                ('server_local', models.CharField(max_length=100, verbose_name='\u6240\u5728\u8282\u70b9')),
                ('server_sertype', models.CharField(choices=[('\u4e1a\u52a1\u670d\u52a1\u5668', '\u4e1a\u52a1\u670d\u52a1\u5668'), ('\u5e73\u53f0\u670d\u52a1\u5668', '\u5e73\u53f0\u670d\u52a1\u5668'), ('\u753b\u9762\u5408\u6210\u670d\u52a1\u5668', '\u753b\u9762\u5408\u6210\u670d\u52a1\u5668'), ('\u6570\u636e\u5e93\u670d\u52a1\u5668', '\u6570\u636e\u5e93\u670d\u52a1\u5668'), ('\u4e2d\u95f4\u4ef6\u670d\u52a1\u5668', '\u4e2d\u95f4\u4ef6\u670d\u52a1\u5668'), ('\u5176\u4ed6', '\u5176\u4ed6')], max_length=100, verbose_name='\u670d\u52a1\u5668\u7c7b\u578b')),
                ('server_ip', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u5668IP\u5730\u5740')),
                ('server_signer', models.CharField(default='system', max_length=100, verbose_name='\u767b\u8bb0\u4eba')),
                ('server_signtime', models.DateField(auto_now_add=True)),
                ('server_remarks', models.CharField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='echo.Node')),
            ],
        ),
    ]
